# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
#
# HTML Emojis: https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb/

matches:

  # User story
  - trigger: "-:story"
    replace: "Story\n\n\n---\n\nBackground\n\n\n---\n\nWhat Needs to Be Done\n\n\n---\n\nMisc\n"

  # Daily Summary - Subject
  - trigger: "-:dss"
    replace: "{{mydate}} Update"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Daily Summary - Body
  - trigger: "-:dsb"
    html: "Howdy &#128075;<br /><br />Below you will find a summary of the team's activities for today. Please let me know if you have any questions.<br /><br /><ul><li></li></ul><br />I hope you've had a great day,<br /><br />Joshua"

  # Weekly Summary - Subject
  - trigger: "-:wss"
    replace: "{{subject}}"
    vars:
      - name: subject
        type: shell
        params:
          cmd: "echo \"Weekly Summary - Starting: $(date -v +Mon '+%Y-%m-%d') | Ending: $(date -v +Fri '+%Y-%m-%d')\""

  # Weekly Summary - Body
  - trigger: "-:wsb"
    html: "Howdy &#128075;<br /><br />Below you will find a summary of the team's activities for this week. Please let me know if you have any questions.<br /><br /><ul><li><strong>MONDAY</strong><br />&nbsp;</li><li><strong>TUESDAY</strong><br />&nbsp;</li><li><strong>WEDNESDAY</strong><br />&nbsp;</li><li><strong>THURSDAY</strong><br />&nbsp;</li><li><strong>FRIDAY</strong><br />&nbsp;</li></ul><br />I hope you've had a great day,<br /><br />Joshua"

  # Messaging - Pinned Team Status
  - trigger: "-:status"
    replace: "Current Focus:\n\nTeam Member = Task\n\n---Out:\n\nTeam Member = Day"

  # Coffee Chat - Subject
  - trigger: "-:ccs"
    replace: "Coffee Chats ☕️"

  # Coffee Chat - Body
  - trigger: "-:ccb"
    replace: "Hi all,\n\nThe coffee chat pairing for this week can be found below. We’ll be working through different ways of handling this in an automated fashion over time. If you’ve found yourself meeting the same person more than once in a row, please let the group know so we can make arrangements.\n\nPlease contact the other people in your grouping below and make arrangements.\n\nThe Coffee Chat Crew ☕️\n\n\n-- pairs --\n"

  # Print the current date
  - trigger: "-:date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Team Sync - Subject
  - trigger: "-:tss"
    replace: "{{mydate}} Team Sync Agenda"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Team Sync - Body
  - trigger: "-:tsb"
    replace: "Hi All,\n\nThis is the agenda for today’s meeting:\n\n* Parking Lot – Unaccounted for Items.\n\nJoshua"

  # Print the output of a shell command
  - trigger: "-:shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
