# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
#
# HTML Emojis: https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb/

matches:

  # User story
  - trigger: "-:story"
    replace: "Story\n\n\n---\n\nBackground\n\n\n---\n\nWhat Needs to Be Done\n\n\n---\n\nMisc\n"

  # Daily Summary - Subject
  - trigger: "-:dss"
    replace: "{{mydate}} Update"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Daily Summary - Body
  - trigger: "-:dsb"
    html: "Howdy &#128075;<br /><br />Below you will find a summary of the team's activities for today. Please let me know if you have any questions.<br /><br /><ul><li></li></ul><br />I hope you've had a great day,<br /><br />Joshua"

  # Weekly Summary - Subject
  - trigger: "-:wss"
    replace: "{{subject}}"
    vars:
      - name: subject
        type: shell
        params:
          cmd: "echo \"Weekly Summary - Starting: $(date -v -Mon '+%Y-%m-%d') | Ending: $(date -v +Fri '+%Y-%m-%d')\""

  # Weekly Summary - Body
  - trigger: "-:wsb"
    html: "Howdy &#128075;<br /><br />Below you will find a summary of the team's activities for this week. Please let me know if you have any questions.<br /><br /><ul><li><strong>MONDAY</strong><br />&nbsp;</li><li><strong>TUESDAY</strong><br />&nbsp;</li><li><strong>WEDNESDAY</strong><br />&nbsp;</li><li><strong>THURSDAY</strong><br />&nbsp;</li><li><strong>FRIDAY</strong><br />&nbsp;</li></ul><br />I hope you've had a great week,<br /><br />Joshua"

  # Coffee Chat - Subject
  - trigger: "-:ccs"
    replace: "Coffee Chats ☕️"

  # Coffee Chat - Body
  - trigger: "-:ccb"
    html: "Hi all,<br /><br />The coffee chat pairing for this week can be found below. If you've found yourself meeting the same person more than once in a row, please let the group know.<br /><br />Please contact the other people in your grouping below to schedule your Coffee Chat.<br /><br />The Coffee Chat Crew &#9749;<br /><br /><br />-- pairs --<br /><br />"

  # Print the current date
  - trigger: "-:date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Team Sync - Body
  - trigger: "-:tsb"
    html: "Hi All,<br /><br />This is the agenda for today's meeting:<br /><br /><ul><li></li><li>Parking Lot - Unaccounted for Items.</li></ul><br />Joshua"

  # TypeScript - Add Testing to Project
  - trigger: "-:tstest"
    replace: "\"itest\": \"npx tsx --test $(find . -name \\\"*.itest.ts\\\")\",\n\"itest:only\": \"npx tsx --test --test-only $(find . -name \\\"*.itest.ts\\\")\",\n\"itest:watch\": \"npx tsx --test --watch $(find . -name \\\"*.itest.ts\\\")\",\n\"itest:watch:only\": \"npx tsx --test --test-only --watch $(find . -name \\\"*.itest.ts\\\")\",\n\"test\": \"npx tsx --test $(find . -name \\\"*.test.ts\\\")\",\n\"test:only\": \"npx tsx --test --test-only $(find . -name \\\"*.test.ts\\\")\",\n\"test:watch\": \"npx tsx --test --watch $(find . -name \\\"*.test.ts\\\")\",\n\"test:watch:only\": \"npx tsx --test --test-only --watch $(find . -name \\\"*.test.ts\\\")\"\n"

  # JavaScript - Add Testing to Project
  - trigger: "-:jstest"
    replace: "\"test\": \"node --test\",\n\"test:only\": \"node --test --test-only\",\n\"test:watch\": \"node --test --watch\",\n\"test:watch:only\": \"node --test --test-only --watch\"\n"

    # Streaming: YouTube - Chillhop
  - trigger: "-:stch"
    replace: "Music provided by Chillhop Music: https://chillhop.ffm.to/creatorcred"

