import = ["~/.config/alacritty/themes/themes/rose-pine-dawn.toml"]

[font]
bold = { family = "SF Mono", style = "Bold" }
bold_italic = { family = "SF Mono", style = "Bold Italic" }
italic = { family = "SF Mono", style = "Italic" }
normal = { family = "SF Mono", style = "Regular" }
offset.y = 8
size = 13.0

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
decorations = "buttonless"
dynamic_padding = true
padding = { x = 24, y = 24 }
option_as_alt = "Both"
