import = ["~/.config/alacritty/themes/themes/rose-pine-dawn.toml"]

[font]
bold = { family = "SF Mono", style = "Bold" }
bold_italic = { family = "SF Mono", style = "Bold Italic" }
italic = { family = "SF Mono", style = "Italic" }
normal = { family = "SF Mono", style = "Regular" }
offset.y = 18
size = 14.0

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
blur = true
decorations = "buttonless"
dynamic_padding = true
opacity = 0.95
option_as_alt = "Both"
padding = { x = 16, y = 16 }
